# Generated by Django 5.2.6 on 2025-09-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='co2_kg',
            field=models.FloatField(default=0.0),
        ),
    ]
